name: Release

on:
  push:
    tags: [ v\d+\.\d+\.\d+ ]

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    outputs:
      release_id: ${{ steps.create-release.outputs.id }}
      release_body: "${{ steps.tag.outputs.message }}"

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Get tag message
        id: tag
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$(git tag -l --format='%(contents)' ${{ steps.get_version.outputs.version }})" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          name: ${{ steps.get_version.outputs.version }}
          tag: ${{ steps.get_version.outputs.version }}
          body: "${{ steps.tag.outputs.message }}"

  build-tauri-renderer:
    needs: create-release
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.0

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          override: true

      - name: install frontend dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Change Version
        env:
          VERSION: "${{ steps.get_version.outputs.version-without-v }}"
        run: make change-version change-package-version

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: build tauri renderer
        run: pnpm build-tauri-renderer

      - uses: actions/upload-artifact@v4
        with:
          name: tauri-renderer
          path: dist/tauri/

  build-tauri:
    needs: [create-release, build-tauri-renderer]
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-latest
            arch: x86_64
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            arch: aarch64
            rust_target: aarch64-apple-darwin

    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.config.rust_target }}
          toolchain: nightly
          override: true

      - name: Install frontend dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install dependencies (mac only)
        run: |
          rustup target add aarch64-apple-darwin

      - name: Change Version
        env:
          VERSION: "${{ steps.get_version.outputs.version-without-v }}"
        run: make change-version change-package-version

      - uses: actions/download-artifact@v4
        with:
          name: tauri-renderer
          path: dist/tauri

      - name: Install Cargo Tauri for info
        run: cargo install tauri-cli --version "=2.8.4" --locked

      - name: Tauri info
        run: cargo tauri info

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        if: matrix.config.arch != 'aarch64'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          releaseBody: ${{ needs.create-release.outputs.release_body }}
          tauriScript: cargo tauri

      - name: Build Tauri App (macOS aarch64)
        uses: tauri-apps/tauri-action@v0
        if: matrix.config.arch == 'aarch64'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          releaseBody: ${{ needs.create-release.outputs.release_body }}
          args: --target aarch64-apple-darwin
          tauriScript: cargo tauri

  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    needs: [create-release, build-tauri]

    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })
